config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :answers
  resources :questions
  resources :orders
  resources :reviews
  resources :categories
  resources :products do 
    resources :images, only: [:create, :destroy]
  end
  resources :users
  resource :sessions, only: [:new, :create, :destroy]

  post '/cart/add', to: 'shopping_cart#add_item'
  post '/cart/remove', to: 'shopping_cart#remove_item'
  post '/cart/edit', to: 'shopping_cart#adjust_quantity'
  get '/cart', to: 'shopping_cart#show'

  post '/cart/submit', to: 'orders#create_from_cart'

  get '/users/:id/orders', to: 'orders#user_orders'

  get '/sessions/request_password', to: 'sessions#request_password'
  post '/sessions/request_password', to: 'sessions#send_new_password_key'

  get '/sessions/reset_password', to: 'sessions#new_password'
  post '/sessions/reset_password', to: 'sessions#reset_password'

  get '/dashboard', to: 'home#dashboard'

  get '/users/:id/token', to: 'users#show_token', as: :show_token
  post '/users/:id/token', to: 'users#generate_token', as: :generate_token

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :reviews, only: [:index, :show, :create]
      resources :questions, only: [:index, :show, :create]
      resources :answers, only: [:index, :show, :create]
      resources :orders, only: [:index, :show, :create]
      get '/user', to: 'users#show'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  username        :string
#  name            :string
#  last_name       :string
#  address         :string
#  phone_number    :string
#  is_admin        :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  avatar          :string
#  token           :string
#
# Indexes
#
#  index_users_on_email     (email) UNIQUE
#  index_users_on_token     (token) UNIQUE
#  index_users_on_username  (username) UNIQUE
#

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_secure_password

  validates :password, presence: { on: :create }, length: { minimum: 6 },
                       allow_blank: { on: :update }
  validates :email, presence: true, uniqueness: true, allow_blank: false,
                    format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :username, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :phone_number, allow_blank: true, format: /\A\+?\d{8,11}\z/i

  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :question_votes, dependent: :destroy
  has_many :voted_questions, through: :question_votes, source: :question
  has_many :answer_votes, dependent: :destroy
  has_many :voted_answers, through: :answer_votes, source: :answer

  def gen_token
    self.token = SecureRandom.hex(128)
    self.token = SecureRandom.hex(128) until save
  end
end

app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < ApiController
    before_action :authenticate

    def show
      @user = User.includes(:reviews, :questions, :answers, :orders).find(@current_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :show_token, :generate_token]
  before_action :check_permission, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    return unless authenticated_admin?
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit  
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        SignupMailer.signup_mail(@user).deliver_later
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render root_path, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/:id/token
  def show_token
    @user.gen_token if @user.token.nil?
  end

  # POST /users/:id/token
  def generate_token
    @user.gen_token
    flash[:notice] = "Successfully generated new token."
    redirect_to show_token_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :name, :last_name, :address, :phone_number, :password, :avatar)
    end

    def check_permission
      if admin? or current_user&.id == @user.id
        return true  
      end
      flash[:alert] = "Permission denied"
      redirect_to root_path
      return false
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= simple_form_for user, html: {id: "signup-form", class: "signup-container"} do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tbody>
      <tr>
        <td width="15%"><%= label_tag(:username, "Username :") %></td>
        <td width="75%"><%= f.input :username, label: false%></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:name, "Name :") %></td>
        <td width="75%"><%= f.input :name, label: false %></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:last_name, "Last Name :") %></td>
        <td width="75%"><%= f.input :last_name, label: false %></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:email, "Email :") %></td>
        <td width="75%"><%= f.input :email, label: false , pattern: "^([^@\\s]+)@((?:[-a-z0-9]+\\.)+[a-z]{2,})$", input_html: {title: "Email format: example@example.com"}%></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:address, "Address :") %></td>
        <td width="75%"><%= f.input :address, label: false %></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:phone_number, "Phone Number :") %></td>
        <td width="75%"><%= f.input :phone_number, label: false , pattern: "^\\+?\\d{8,11}$", input_html: {title: "Phone number must contain 8-11 digits and start or not with a \"+\" symbol"}%></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:password, "Password :") %></td>
        <td width="75%"><%= f.input :password, label: false , input_html: { minlength: 6 }%></td>
      </tr>
      <tr>
        <td width="15%"><%= label_tag(:avatar, "Avatar :") %></td>
        <td width="15%"><%= f.file_field :avatar %></td>
      </tr>
    </tbody>
</table>

  <div class="actions">
    <p><%= f.submit submit_message %></p>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= simple_form_for user, html: {id: "signup-form", class: "signup-container"} do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :username %>
  <%= f.input :name %>
  <%= f.input :last_name %>
  <%= f.input :email , pattern: "^([^@\\s]+)@((?:[-a-z0-9]+\\.)+[a-z]{2,})$", input_html: {title: "Email format: example@example.com"}%>
  <%= f.input :address %>
  <%= f.input :phone_number , pattern: "^\\+?\\d{8,11}$", input_html: {title: "Phone number must contain 8-11 digits and start or not with a \"+\" symbol"}%>
  <%= f.input :password , input_html: { minlength: 6 }%>
  <div>
    <label>Avatar:</label>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <p><%= f.submit submit_message %></p>
  </div>

<% end %>

app/views/users/edit.html.erb
<div id="wrap">

<h1>Editing User</h1>

<%= render 'edit_form', user: @user, submit_message: "Update Account Information" %>

<%= link_to 'Cancel', @user %>

</div>

app/views/users/index.html.erb
<h1>Users</h1>
 <a class="new-button" href=<%=new_user_path%>>Add New User</a>
 <br><br>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Username</th>
      <th>Name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Is admin</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.address %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.is_admin %></td>
        <td><%= user.password %></td>
        <td><%= link_to fa_icon("search"), user %></td>
        <td><%= link_to fa_icon("edit"), edit_user_path(user) %></td>
        <td><%= link_to fa_icon("trash-o"), user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="signup">
<h1 class="signup-header">Sign Up</h1>

<%= render 'form', user: @user, submit_message: "Sign Up" %>
</div>

app/views/users/show.html.erb
<div class="centered-div user-info">

  <h2> Your Account </h2>

  <% if !@user.avatar.file.nil? %>
    <%= image_tag @user.avatar.url, id: "avatar-show"%>
  <% end %>

  <table class="no-border user-show">
    <tbody class="no-border">
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Username:</strong>
        </td>
        <td class="no-border" valign="top">
            <%= @user.username %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Name:</strong>
        </td>
        <td class="no-border" valign="top">
            <%= "#{@user.name} #{@user.last_name}" %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Email:</strong>
        </td>
        <td class="no-border" valign="top">
            <%= @user.email %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Address:</strong>
        </td>
        <td class="no-border" valign="top">
              <%= @user.address %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Phone number:</strong>
        </td>
        <td class="no-border" valign="top">
            <%= @user.phone_number %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
           <%= link_to 'Edit Account Information', edit_user_path(@user) %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
           <%= link_to 'Developer Token', "/users/#{@user.id}/token", {class: "small-link"} %>
        </td>
      </tr>

    </tbody>
  </table>

</div>

app/views/users/show_token.erb
<div class="centered-div user-info">

  <h2> Developer Token </h2>

  <table class="no-border user-show">
    <tbody class="no-border">
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Username:</strong>
        </td>
        <td class="no-border" valign="top">
            <%= @user.username %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
            <strong>Token:</strong>
        </td>
        <td class="no-border" valign="top">
          <span class="break-inline-long">
            <%= "#{@user.token}" %>
          </span>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
           <%= button_to 'Generate New Token', generate_token_url, {class: "small-link"} %>
        </td>
      </tr>
      <tr class="no-border">
        <td class="no-border" valign="top">
           <%= link_to 'Back', user_path(@user), {class: "small-link"} %>
        </td>
      </tr>

    </tbody>
  </table>

</div>