config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :answers
  resources :questions
  resources :orders
  resources :reviews
  resources :categories
  resources :products do 
    resources :images, only: [:create, :destroy]
  end
  resources :users
  resource :sessions, only: [:new, :create, :destroy]

  post '/cart/add', to: 'shopping_cart#add_item'
  post '/cart/remove', to: 'shopping_cart#remove_item'
  post '/cart/edit', to: 'shopping_cart#adjust_quantity'
  get '/cart', to: 'shopping_cart#show'

  post '/cart/submit', to: 'orders#create_from_cart'

  get '/users/:id/orders', to: 'orders#user_orders'

  get '/sessions/request_password', to: 'sessions#request_password'
  post '/sessions/request_password', to: 'sessions#send_new_password_key'

  get '/sessions/reset_password', to: 'sessions#new_password'
  post '/sessions/reset_password', to: 'sessions#reset_password'

  get '/dashboard', to: 'home#dashboard'

  get '/users/:id/token', to: 'users#show_token', as: :show_token
  post '/users/:id/token', to: 'users#generate_token', as: :generate_token

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :reviews, only: [:index, :show, :create]
      resources :questions, only: [:index, :show, :create]
      resources :answers, only: [:index, :show, :create]
      resources :orders, only: [:index, :show, :create]
      get '/user', to: 'users#show'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  before_action :set_cart

  def add_item
    quantity = cart_params[:quantity].to_i
    if quantity > 0
      pid = cart_params[:product_id]
      @cart[pid] = (@cart[pid] || 0) + cart_params[:quantity]
    end
    respond_to do |format|
      format.html do
        flash[:notice] = 'This product was successfully added to your Shopping Cart'
        redirect_back(fallback_location: root_path)
      end
      format.js
    end
  end

  def remove_item
    @product_id = cart_params[:product_id]
    @cart.delete(@product_id)

    @total = calculate_total

    respond_to do |format|
      format.html do
        flash[:notice] = 'The item was successfully removed from your Shopping Cart'
        redirect_back(fallback_location: root_path)
      end
      format.js
    end
  end

  def adjust_quantity
    @product_id = cart_params[:product_id]
    @product = Product.find(@product_id)
    @quantity = cart_params[:quantity]
    if @quantity > 0
      @cart[@product_id] = @quantity
    else
      @cart.delete(@product_id)
    end

    @total = calculate_total

    respond_to do |format|
      format.html do
        flash[:notice] = 'Your Shopping Cart has been updated successfuly'
        redirect_back(fallback_location: root_path)
      end
      format.js
    end
  end

  def show
    @products = Product.find(@cart.keys).map do |p|
      [p, @cart[p.id.to_s]]
    end
    @total = @products.map { |p, q| p.real_prize * q }.sum
  end

  private

  def calculate_total
    products = Product.find(@cart.keys).map do |p|
      [p, @cart[p.id.to_s]]
    end
    products.map { |p, q| p.real_prize * q }.sum
  end

  def set_cart
    @cart = session['cart'] ||= {}
  end

  def cart_params
    parameters = params.require(:cart).permit(:product_id, :quantity)
    parameters[:quantity] = parameters[:quantity].to_i
    parameters
  end
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/shopping_cart/add_item.js.erb
<%= render partial: 'flash_message', locals: {message: "This product was successfully added to your Shopping Cart!", timeout: 3500} %>

app/views/shopping_cart/adjust_quantity.js.erb
<%= render partial: 'flash_message', locals: {message: "Your Shopping Cart has been updated successfuly!", timeout: 3500} %>

var quantity = document.querySelector("tr[data-product-id='<%= @product_id %>'] td[data-attribute='quantity']")
var cost = document.querySelector("tr[data-product-id='<%= @product_id %>'] td[data-attribute='total-cost']")
var total_cost = document.querySelector("p[data-attribute='total-cost-global']")

quantity.innerHTML = "<%= @quantity %>"
cost.innerHTML = "$<%= @quantity * @product.real_prize %>"
total_cost.innerHTML = "<strong> Total: $<strong><%= @total %>"

app/views/shopping_cart/remove_item.js.erb
<%= render partial: 'flash_message', locals: {message: "The item was successfully removed from your Shopping Cart!", timeout: 3500} %>
var row = document.querySelector("tr[data-product-id='<%= @product_id %>'")
row.parentNode.removeChild(row);

var total_cost = document.querySelector("p[data-attribute='total-cost-global']")
total_cost.innerHTML = "<strong> Total: $<strong><%= @total %>"

app/views/shopping_cart/show.html.erb
<% if @products.count > 0 %>

  <table id="unfixed-table">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total Cost</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product, quantity| %>
        <tr data-product-id="<%= product.id %>">
          <td><%= link_to fa_icon("search"), product %></td>
          <td width="15%"><%= product.name %></td>
          <td width="15%">$<%= product.real_prize %></td>
          <td width="15%" data-attribute="quantity"><%= quantity %></td>
          <td width="15%" data-attribute="total-cost">$<%= product.real_prize * quantity %></td>
          <td width="30%">
          <%= form_tag(cart_edit_path,method:"post", remote:true) do %>
            <%= hidden_field_tag("cart[product_id]", product.id)%>
            <%= number_field("cart","quantity", value: quantity, min: 1) %>
            <%= submit_tag("Change Quantity")%>
          <% end %>
          </td>
          <td width="15%">
          <%= form_tag(cart_remove_path,method:"post", remote:true) do %>
            <%= hidden_field_tag("cart[product_id]", product.id)%>
            <%= button_tag(type: "submit") do%>
              <% fa_icon("trash-o")%>
            <%end%>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <p data-attribute="total-cost-global">
    <strong> Total: $<strong><%= @total %>
  </p>

  <br>

  <% if current_user %>
    <%= form_tag(cart_submit_path, method:"post") do %>
      <%= button_tag(type: "submit", class:"centered_button") do%>
        <% fa_icon("share-square-o", text: "Place Order!")%>
      <%end%>
    <% end %>
  <% else %>
    <p> You must <%= link_to('Log In', new_sessions_path) %> to checkout your cart! </p>
  <% end %>
<% else %>
  <p> Your Cart is Empty! Head over to the Products section to fill your cart!</p>
<% end %>

<!--
<% @products.each do |product,quantity|%>
  <div>
  <%= product.name %>
  <%= quantity %>
  <%= form_tag(cart_edit_path,method:"post") do %>
    <%= hidden_field_tag("cart[product_id]", product.id)%>
    <%= number_field("cart","quantity", value: quantity, min: 1) %>
    <%= submit_tag("Change Quantity")%>
  <% end %>
  <%= form_tag(cart_remove_path,method:"post") do %>
    <%= hidden_field_tag("cart[product_id]", product.id)%>
    <%= button_tag(type: "submit") do%>
      <% fa_icon("trash-o")%>
    <%end%>
  <% end %>
  </div>
<% end %>
-->