config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :answers
  resources :questions
  resources :orders
  resources :reviews
  resources :categories
  resources :products do 
    resources :images, only: [:create, :destroy]
  end
  resources :users
  resource :sessions, only: [:new, :create, :destroy]

  post '/cart/add', to: 'shopping_cart#add_item'
  post '/cart/remove', to: 'shopping_cart#remove_item'
  post '/cart/edit', to: 'shopping_cart#adjust_quantity'
  get '/cart', to: 'shopping_cart#show'

  post '/cart/submit', to: 'orders#create_from_cart'

  get '/users/:id/orders', to: 'orders#user_orders'

  get '/sessions/request_password', to: 'sessions#request_password'
  post '/sessions/request_password', to: 'sessions#send_new_password_key'

  get '/sessions/reset_password', to: 'sessions#new_password'
  post '/sessions/reset_password', to: 'sessions#reset_password'

  get '/dashboard', to: 'home#dashboard'

  get '/users/:id/token', to: 'users#show_token', as: :show_token
  post '/users/:id/token', to: 'users#generate_token', as: :generate_token

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :reviews, only: [:index, :show, :create]
      resources :questions, only: [:index, :show, :create]
      resources :answers, only: [:index, :show, :create]
      resources :orders, only: [:index, :show, :create]
      get '/user', to: 'users#show'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
    validates :name, presence: true, allow_blank: false, uniqueness: true

    has_many :product_tags, dependent: :destroy
    has_many :products, through: :product_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :authenticated_admin?, only:[:new, :create, :edit, :update, :destroy, :index]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %>

app/views/tags/index.html.erb
<h1>Tags</h1>
 <a class="new-button" href=<%=new_tag_path%>>Add New Tag</a>
 <br><br>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.id %></td>
        <td><%= tag.name %></td>
        <td><%= link_to fa_icon("search"), tag %></td>
        <td><%= link_to fa_icon("edit"), edit_tag_path(tag) %></td>
        <td><%= link_to fa_icon("trash-o"), tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<h1 id="form-title">New Tag</h1>

<%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @tag.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %>