config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :answers
  resources :questions
  resources :orders
  resources :reviews
  resources :categories
  resources :products do 
    resources :images, only: [:create, :destroy]
  end
  resources :users
  resource :sessions, only: [:new, :create, :destroy]

  post '/cart/add', to: 'shopping_cart#add_item'
  post '/cart/remove', to: 'shopping_cart#remove_item'
  post '/cart/edit', to: 'shopping_cart#adjust_quantity'
  get '/cart', to: 'shopping_cart#show'

  post '/cart/submit', to: 'orders#create_from_cart'

  get '/users/:id/orders', to: 'orders#user_orders'

  get '/sessions/request_password', to: 'sessions#request_password'
  post '/sessions/request_password', to: 'sessions#send_new_password_key'

  get '/sessions/reset_password', to: 'sessions#new_password'
  post '/sessions/reset_password', to: 'sessions#reset_password'

  get '/dashboard', to: 'home#dashboard'

  get '/users/:id/token', to: 'users#show_token', as: :show_token
  post '/users/:id/token', to: 'users#generate_token', as: :generate_token

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
      resources :reviews, only: [:index, :show, :create]
      resources :questions, only: [:index, :show, :create]
      resources :answers, only: [:index, :show, :create]
      resources :orders, only: [:index, :show, :create]
      get '/user', to: 'users#show'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  details     :text
#  prize       :integer
#  stock       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  images      :json
#  discount    :integer
#

class Product < ApplicationRecord
  mount_uploaders :images, ProductImageUploader

  validates :name, presence: true, allow_blank: false
  validates :prize, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :discount, allow_nil: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  has_many :reviews, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories

  def add_category; end

  def remove_category; end

  def add_tag; end

  def remove_tag; end

  def average_score
    reviews = self.reviews.map(&:score)
    if !reviews.empty?
      reviews.sum / reviews.length
    else
      0
    end
  end

  def root_category
    cat = categories.first
    return cat unless cat
    while parent = cat.parent
      cat = parent
    end
    cat
  end

  def real_prize
    if self.discount
      (self.prize*(1-self.discount/100.0)).to_i
    else
      self.prize
    end
  end
end

app/controllers/api/v1/products_controller.rb
module Api::V1
  class ProductsController < ApiController
    before_action :authenticate
    
    def index
      @products = Product.all
    end

    def show
      @product = Product.includes(:reviews, :questions).find(params[:id])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticated_admin?, only: %i[create edit update destroy]

  # GET /products
  # GET /products.json
  def index
    respond_to do |format|
      @category_index = category_tree
      category_id = params[:category_id]
      @products = Product.all.order(:id).includes(:categories).includes(:tags)
      if category_id
        category_id = category_id.to_i
        @category = Category.find(category_id)
        categories = @category.extended_children
        @products = @products.select { |x| x.categories.any? { |c| categories.include? c } }
        @cat_name = @category.name
      else
        @cat_name = 'All products'
      end

      @in_offer = @products.select { |x| x.discount && x.discount > 0 }
      @rest = @products - @in_offer

      format.html
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
    @question = Question.new

    orders = Order.includes(:products).find(OrderedProduct.where(product_id: @product.id).pluck(:order_id))
    same_products = orders.map{|o| o.products.reject{|p| p.id == @product.id}}.flatten
    counter = {}
    for product in same_products
      if counter[product]
        counter[product] += 1
      else
        counter[product] = 1
      end
    end
    @most_bought = counter.sort_by{|key, value| value}.reverse.map{|x| x.first}[0...3]
    


  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    # Solo el admin puede crear y editar productos, asique no tiene mucho sentido validar estas acciones
    # (se le da poder total al admin, no tiene sentido restringirlo)
    ProductCategory.create(product_id: @product.id, category_id: association_changes[:add_category]).id unless association_changes[:add_category].blank?
    ProductCategory.where(category_id: association_changes[:remove_category], product_id: @product.id).delete_all unless association_changes[:remove_category].blank?

    ProductTag.create(product_id: @product.id, tag_id: association_changes[:add_tag]).id unless association_changes[:add_tag].blank?
    ProductTag.where(tag_id: association_changes[:remove_tag], product_id: @product.id).delete_all unless association_changes[:remove_tag].blank?

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :details, :prize, :stock, :discount, images: [])
  end

  def association_changes
    params.require(:product).permit(:add_category, :remove_category, :add_tag, :remove_tag)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_card.html.erb
<figure data-tags='<%= product.tags.map{|x| x.name} %>'>
    <%= link_to product do %>
        <% if product.images.length() > 0 %>
        <%= image_tag(product.images.first.url, alt: "unavailable.jpg") %>
        <% else %>
        <%= image_tag("unavailable.jpg") %>
        <% end %>
    <% end %>
            
    <figcaption><%= product.name %></figcaption>
    <% if product.discount && product.discount>0 %>
        <span class="strikethrough-text">$ <%= product.prize %></span>
        - <span class="price" style="color: red;">$ <%= (product.prize*(1-product.discount/100.0)).to_i %> </span>
          <span style="color: red;"> Discount! </span>
    <% else %>
        <span class="price">$ <%= product.prize %></span>
    <% end %>

    <%= form_tag("/cart/add",method:"post", class:"button", remote: true) do %>
    <%= hidden_field_tag("cart[product_id]", product.id)%>
    <%= hidden_field_tag("cart[quantity]", 1) %>
    <%= submit_tag("Add to Cart", class:"button")%>
    <% end %>

    <% if current_user&.is_admin %>
    <%= link_to fa_icon("edit"), edit_product_path(product) %>

    <%= link_to fa_icon("trash-o"), product, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</figure>

app/views/products/_cards.html.erb
  <div>
    <input type="text" id="filterInput" onkeyup="filter()" placeholder="Filter by name or tags...">    
  </div>
  <div>
    Filter by Price:
    <input type="number" id="low" class="priceFilter" onkeyup="filter()" onchange="filter()" min="0">
    -
    <input type="number" id="high" class="priceFilter" onchange="filter()" min="0">
  </div>

   <br>
   <div id="productCards">
      <% (@in_offer + @rest).each do |product| %>
        <%= render partial: 'card', locals: {product: product} %>
      <% end %>
    </div>

app/views/products/_edit_form.html.erb
<%= simple_form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
    <tbody>
      <tr>
        <td width="25%"><%= label_tag(:name, "Name: ") %></td>
        <td width="75%"><%= f.input :name, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:description, "Description: ") %></td>
        <td width="75%"><%= f.input :description, label: false, :input_html => {style: 'width: 80%; height: 80px;'}%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:details, "Details: ") %></td>
        <td width="75%"><%= f.input :details, label: false, :input_html => {style: 'width: 80%; height: 80px;'}%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:prize, "Prize: ") %></td>
        <td width="75%"><%= f.input :prize, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:stock, "Stock: ") %></td>
        <td width="75%"><%= f.input :stock, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:add_category, "Add category: ") %></td>
        <td width="75%"><%= f.input :add_category, collection: (Category.all - @product.categories), label_method: :name, value_method: :id, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:remove_category, "Remove category: ") %></td>
        <td width="75%"><%= f.input :remove_category, collection: @product.categories, label_method: :name, value_method: :id, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:add_tag, "Add tag: ") %></td>
        <td width="75%"><%= f.input :add_tag, collection: (Tag.all - @product.tags), label_method: :name, value_method: :id, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:remove_tag, "Remove tag: ") %></td>
        <td width="75%"><%= f.input :remove_tag, collection: @product.tags, label_method: :name, value_method: :id, label: false%></td>
      </tr>
      <tr>
        <td width="25%"><%= label_tag(:discount, "Discount: ") %></td>
        <td width="75%"><%= f.input :discount, label: false%></td>
      </tr>
    </tbody>
</table>

  <div class="actions">
    <p><%= f.submit %></p>
  </div>


<% end %>

app/views/products/_new_form.html.erb
<%= simple_form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :details %>
  <%= f.input :prize %>
  <%= f.input :stock %>

  <%= f.file_field :images, multiple: true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/backup_index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Details</th>
      <th>Prize</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.details %></td>
        <td><%= product.prize %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/edit.html.erb
<div class="centered-div">

  <h1>Editing Product</h1>

  <%= render 'edit_form', product: @product %>

  <h2> Images </h2>


  <table class="no-border">
    <tbody class="no-border">

      <% @product.images.each_with_index do |img, index| %>
      <tr class="no-border">
        <td class="no-border"><%= image_tag img.url %> </td>
        <% if admin? %>
          <td class="del-icon"> <%= link_to fa_icon("trash"), product_image_path(@product, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" }%> </td>
        <% end %>
      <tr>
      <% end %>
    </tbody>
  </table>

  <% if admin? %>
    <h1>Add more images</h1>

    <%= form_for @product, url: product_images_path(@product), method: :post do |f| %> 
      <%= f.file_field :images, multiple: true, required: true %>
      <%= f.submit "Add More Images" %>
    <% end %>
  <% end %>

  <br>
  <br>    

  <%= link_to 'Show', @product %>

</div>

app/views/products/index.html.erb
<div id="wrap">
    <h1>Products</h1>
      <% if current_user&.is_admin %>
        <a class="new-button" href=<%=new_product_path%>>Add New Product</a>
      <% end %>
  
  
  <% if @category %>
    <h2> Category: <%= @category.name %> </h2>
  <% else %>
    <h2> All products </h2>
  <% end %>

  <div id="category_tree" class="transition">
    
    
    <div class="categories-title transition">
      Categories
    </div>

    <div class="category">
      <%= link_to "All Products", products_path, remote: true %>
    </div>
    <% @category_index.each do |category, depth| %>
      <div class="category" style= <%= "padding-left:#{5+12*depth}px;" %> >
        <%= link_to category.name, products_path(category_id: category.id), remote: true %>
      </div>
    <% end %>
    <!-- dafuq this do?: <a href="?active=true"> -->
  </div>

  <div id="columns" class="columns_4">
	  <%= render :partial => "cards" %>
  </div>

app/views/products/index.js.erb
$('#columns').html("<%= escape_javascript(render partial: 'cards', locals: { items: @products } ) %>");
$('h2').text("<%= @cat_name %>")

app/views/products/new.html.erb
<h1 id="form-title">New Product</h1>

<%= render 'new_form', product: @product %>

app/views/products/show.html.erb
<% if admin? %>
  <a class="edit-button" href=<%=edit_product_path%>>Edit Product</a>
<% end %>



<table class="no-border">
  <tbody class="no-border">

  <tr class="no-border">
      <td class="no-border" valign="top"> 
  


    <div class="product-single">
      <div class="product-gallery">
        <div id="slider-wrap">
          <ul class="slides">

          <% if @product.images.length() > 0 %>
              <% @product.images.each_with_index do |img, index| %>
                <li class=frame><%= image_tag img.url, class:"gallery-image" %></li> 
              <% end %>
              </ul>
              <ul class="nav-dots">
                <% @product.images.each_with_index do |img, index| %>
                  <% if index != 0 %>
                    <li></li> 
                  <% else %>
                    <li class="active"></li>
                  <% end %>
                <% end %>
            <% else %>
              <li><%= image_tag "unavailable.jpg", class:"gallery-image" %></li>
            <% end %>




          
          </ul>
        </div>
      </div>
    </div>
</td>
      <td class="no-border"  valign="top"> 

    <h1><%= @product.name %></h1>
    <div class="star-ratings-sprite">
      <span style="width:<%= @product.average_score()*20 %>%" class="star-ratings-sprite-rating"></span>
    </div>
    <span id="review-count" class="grey-font">(<%= @product.reviews.length()%> reviews)</span>



    <h3>Description</h3>
    <p>
      <%= @product.description %>
    </p>

    <h3>Details</h3>
    <p>
      <%= @product.details %>
    </p>

    <h3>Price</h3>
    <p>
      <% if @product.discount && @product.discount>0 %>
        <span class="strikethrough-text">$ <%= @product.prize %></span>
        - <span class="price" style="color: red;">$ <%= (@product.prize*(1-@product.discount/100.0)).to_i %> </span>
          <span style="color: red;"> Discount! </span>
      <% else %>
          <span class="price">$ <%= @product.prize %></span>
      <% end %>
    </p>

    <h3>Stock</h3>
    <p>
      <%= @product.stock %>
    </p>

    <h3>Categories</h3>
    <p>
      <ul>
      <% @product.categories.each do |category| %>
        <li><%= category.name %></li>
      <% end%>
      </ul>
    </p>

    <h3>Tags</h3>
    <p>
      <ul>
      <% @product.tags.each do |tag| %>
        <li><%= tag.name %></li>
      <% end%>
      </ul>
    </p>

    <%= form_tag("/cart/add",method:"post", remote: true) do %>
      <%= hidden_field_tag("cart[product_id]", @product.id)%>

      <span class="input-number-decrement">–</span>
      <%= number_field("cart","quantity", value: 1, min: 1, class: "input-number", type: "text") %>
      <span class="input-number-increment">+</span>


      <%= submit_tag("Add to Cart", class: "button2")%>
    <% end %>


    </td>
  </tbody>
</table>

<% if @most_bought.count > 0 %>
  <div id="wrap">
  <h3>Customers who bought this item also bought</h3>
    <div id="columns" class="columns_4">
      <% (@most_bought).each do |product| %>
          <%= render partial: 'card', locals: {product: product} %>
        <% end %>
    </div>
  </div>
<% end %>

  



<div class="tab">
   <button class="tablinks defaultOpen" data-tab="reviews-tab">Reviews</button>
   <button class="tablinks" data-tab="questions-tab">Questions</button>
</div>  


<div class = "reviews-tab tabcontent">
<h2> Reviews </h2>
<div class="amazing-reviews">
  <% @product.reviews.each do |review| %>
    <%= render partial: 'reviews/card', locals: {review: review} %>
  <% end %>
</div>

<% if !@product.reviews.map{|x| x.user_id}.include? current_user&.id %>
  <%= simple_form_for(@review, remote: true) do |f| %>
    <h2> Write new Review </h2>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.input :content, label: false, :input_html => {style: 'width: 800px; height: 180px;'}%>
    <%= f.hidden_field :product_id, value: @product.id %>
    <div style="float:right;">
      <%= f.input :score, input_html: {min: '0', max: '5', step: '0.5'} %>
      <div class="actions" style="float:right;">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
<% end %>

</div>
<div class = "questions-tab tabcontent">
<h2> Questions & Answers </h2>
<div id="questions-div">
  <% @product.questions.each do |question| %>
    <%= render partial: 'questions/card', locals: {question: question} %>
    <% question.answers.each do |answer| %>
      <%= render partial: 'answers/card', locals: {answer: answer} %>
    <% end %>
  <% end %>
</div>

<%= simple_form_for(@question, remote: true) do |f| %>
  <h2> Write new Question </h2>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content, label: false%>
  <%= f.hidden_field :product_id, value: @product.id %>

  <div class="actions" style="float:right;">
    <%= f.submit %>
  </div>
<% end %>

</div>